%YAML:1.0

# data path
pcd_data: /media/xiaochen/xch_disk/TreeScope_dataset/icra_challenge/development_phase/VAT-0723M-05.pcd

# for FEC cluster
min_component_size: 10000
tolorance: 0.05
max_n: 50
merge_dist: 0.1

# to distinguish the cluster type
linearityThres: 0.95
scateringThres: 0.05
upThres: 0.3
clusterHeight: 5

# for tri descriptor
descriptor_near_num: 10
descriptor_min_len: 2
descriptor_max_len: 50
side_resolution: 0.1

# for the registration
candidate_num: 50
rough_dis_threshold: 0.03
vertex_diff_threshold: 0
icp_threshold: 0.0
dist_candi_frames_verify: 1
normal_geo_verify: 1
dis_geo_verify: 0.3
use_matched_num: 4000
