%YAML:1.0

# data path
pcd_data: /media/xiaochen/xch_disk/TreeScope_dataset/icra_challenge/testing_phase/testing-1.pcd
json_data: /media/xiaochen/xch_disk/TreeScope_dataset/icra_challenge/testing_phase/testing-1.json
# for FEC cluster
min_component_size: 100
tolorance: 0.1
max_n: 50

# to distinguish the cluster type
clusterPointsNum: 50            # minimum cluster point's num
linearThres: 0.7                # linearity
planarThres: 0.2                # planarity
scaterThres: 0.2                # scaterring
directThres: 30                # direction threshold
heightThres: 1.0                # height threshold
horizonThres: 3.0               # horizonal threshold

# for fitting cylinders
cyliner_point_num: 50            # minimum point's number for cylinder fitting
model_dist_thres: 0.2             # fitting distance threshold
iteration_num: 2000               # maximum iteration number
min_radius: 0.02                  # minimum radius
max_radius: 1                   # maximum radius
is_opti_cylinder_coeff: 1      # optimize or not

# for fitting circles
circle_point_num: 10          # points number threshold
circle_model_dist_thres: 0.05 # fitting threshold
circle_iteration_num: 20000    # maximum iteration number
circle_min_radius: 0.02       # minimum radius
circle_max_radius: 1        # maximum radius
is_opti_coeff: 0           # optimize or not

# parameters for CSF
bSloopSmooth: 0             # sloop smooth
cloth_resolution: 0.5           # cloth resolution
rigidness: 1                    # rigidness of cloth, 1: soft; 2: midle; 3: rigid
time_step: 0.65                 # step
class_threshold: 0.5            # ooint height threshold to ground 
iterations: 200                 # max iteration

# parameters for Crop tree points
min_height: 9
max_height: 12