%YAML:1.0

# data path
pcd_data: /media/xiaochen/xch_disk/TreeScope_dataset/icra_challenge/development_phase/VAT-1022-A6.pcd

# for FEC cluster
min_component_size: 100
tolorance: 0.2
max_n: 50
merge_dist: 0.1

# to distinguish the cluster type
linearityThres: 0.95
scateringThres: 0.05
upThres: 0.3
clusterHeight: 5

# for tri descriptor
descriptor_near_num: 10
descriptor_min_len: 2
descriptor_max_len: 50
side_resolution: 0.1

# parameters for CSF
bSloopSmooth: 0             # sloop smooth
cloth_resolution: 0.5           # cloth resolution
rigidness: 1                    # rigidness of cloth, 1: soft; 2: midle; 3: rigid
time_step: 0.65                 # step
class_threshold: 0.5            # ooint height threshold to ground 
iterations: 200                 # max iteration
